# Mean, Median, Range
## Man Folder 

The man folder contains a .rd file which contains the documentation for the function mean_median_range, generated by roxygen2. 
The file contains the title and usage of the function, arguments of the function, what the function will return in the value section, a description of what the function does, details highlighting what the function will return if non-numerical values are inputted, and examples for how to use the function. 
